spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/send_to_my_phone
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect